#Project Euler Problem #029: Distinct powers
#How many distinct terms are in the sequence generated by a^b for 2 <= a,b <= 100 

f = []
for a in range(2, 101):
    for b in range(2, 101):
        #print(a,b)
        if a**b not in f:
            f.append(a**b)

print(f)
print(len(f))
